# If you are not sure what all these fields mean, please refer our documentation here:
# http://evalai.readthedocs.io/en/latest/challenge_creation.html#challenge-creation-using-zip-configuration
title: DramaQA Challenge 2019 
short_description: DramaQA Challenge 2019 
description: templates/description.html                              # 유원 : 챌린지 전반에 관련된 description
evaluation_details: templates/evaluation_details.html                # 유원 : DramaQA 모델 평가 메트릭에 관련된 설명(Scene, shot, overall performance) 
terms_and_conditions: templates/terms_and_conditions.html            
image: logo.jpg                                                      # todo : 기천
submission_guidelines: templates/submission_guidelines.html          # todo : 기천
leaderboard_description: 
evaluation_script: evaluation_script.zip
remote_evaluation: False
start_date: 2019-10-15 00:00:00  
end_date: 2019-12-31 23:59:59       
published: True

leaderboard:
  - id: 1
    schema: { "labels": ["Scene-level", "Shot-level", "Total"], "default_order_by": "Total" }

challenge_phases:
  - id: 1
    name: DramaQA Dataset
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    start_date: 2019-10-15 00:00:00
    end_date: 2019-12-05 23:59:59
    test_annotation_file: annotations/test_annotations_testsplit.json # todo : 기천
    codename: test
    max_submissions_per_day: 10
    max_submissions_per_month: 10
    max_submissions: 10

dataset_splits:
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1 
    leaderboard_id: 1 
    dataset_split_id: 1 
    visibility: 3 
    leaderboard_decimal_precision: 2 
    is_leaderboard_order_descending: True
